var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(e){var f=0;return function(){return f<e.length?{done:!1,value:e[f++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};$jscomp.makeIterator=function(e){var f="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];if(f)return f.call(e);if("number"==typeof e.length)return $jscomp.arrayIterator(e);throw Error(String(e)+" is not an iterable or ArrayLike");};
$jscomp.arrayFromIterator=function(e){for(var f,h=[];!(f=e.next()).done;)h.push(f.value);return h};$jscomp.arrayFromIterable=function(e){return e instanceof Array?e:$jscomp.arrayFromIterator($jscomp.makeIterator(e))};$jscomp.getRestArguments=function(){for(var e=Number(this),f=[],h=e;h<arguments.length;h++)f[h-e]=arguments[h];return f};
(function(){var e=function(){var f=function(a){console.error("ringover-sdk: "+a);return!1},h={small:{height:"500px",width:"350px"},medium:{height:"620px",width:"380px"},big:{height:"750px",width:"1050px"},auto:{height:"100%",width:"100%"}},n={width:"60px",height:"6px",backgroundColor:"#eee",boxSizing:"border-box",backgroundClip:"content-box",padding:"7px",cursor:"pointer",borderRadius:"12px"},p={height:"20px",width:"100%",backgroundColor:"white",boxSizing:"border-box",display:"flex",justifyContent:"center",
alignItems:"center",position:"absolute",top:"0"},q=function(a){return JSON.parse(JSON.stringify({changePage:[],hangupCall:[],ringingCall:[],answeredCall:[],dialerReady:[],login:[],logout:[],smsSent:[],smsReceived:[]}))},k=q(),t=function(a,c){var b=document.createElement("IFRAME"),d=document.createElement("DIV"),l;for(l in a)d.style[l]=a[l];b.style.height="100%";b.style.width="100%";b.style.border="none";b.allow="microphone;autoplay;clipboard-read;clipboard-write;";b.id="ringover-iframe-"+c;d.id="ringover-iframe-container-"+
c;d.appendChild(b);return{i:b,d:d}},u=function(a,c){var b=document.createElement("DIV"),d;for(d in a)b.style[d]=a[d];b.id="ringover-tray-"+c;return b},v=function(a){var c=document.createElement("DIV"),b=document.createElement("DIV"),d;for(d in n)b.style[d]=n[d];for(var l in p)c.style[l]=p[l];b.id="ringover-cross-"+a;c.appendChild(b);return b},m=function(a){a.style.opacity="1";a.style.maxHeight="100%";"false"===a.dataset.animation&&(a.style.display="inline-block");return!0},r=function(a,c){var b=a.iframe;
if(c.data&&c.data.action)switch(c.data.action){case "checkSDK":b.contentWindow.postMessage({action:"presenceSDK",location:window.location.origin},"https://app.ringover.com");break;case "changePage":if(a.lastPage===c.data.data.page)break;a.lastPage=c.data.data.page;if(k[c.data.action]){var d=$jscomp.makeIterator(k[c.data.action]);for(b=d.next();!b.done;b=d.next())b=b.value,b(c.data)}break;case "ringingCall":a.show();if(k[c.data.action])for(d=$jscomp.makeIterator(k[c.data.action]),b=d.next();!b.done;b=
d.next())b=b.value,b(c.data);break;default:if(k[c.data.action])for(d=$jscomp.makeIterator(k[c.data.action]),b=d.next();!b.done;b=d.next())b=b.value,b(c.data)}},w=function(a){a.iframe.onmessage=function(){var c=$jscomp.getRestArguments.apply(0,arguments);return r.apply(null,[a].concat($jscomp.arrayFromIterable(c)))};window.onmessage=function(){var c=$jscomp.getRestArguments.apply(0,arguments);return r.apply(null,[a].concat($jscomp.arrayFromIterable(c)))}},g=function(a){var c=this;a=void 0===a?{}:a;
this.id=parseInt(((new Date).getTime()+Math.random()).toString().replace(".","")).toString(16);this.status=-1;this.display=!1;this.style=JSON.parse(JSON.stringify({position:"fixed",display:"inline-block",boxSizing:"border-box",zIndex:"9999",boxShadow:"0px 0px 10px #aaa",borderRadius:"10px",border:"none",transition:"all .5s linear",maxHeight:"0px",opacity:"0"}));if("object"!==typeof a||Array.isArray(a)||null===a)return this.status=0,f("Options object not conform. Please referer to documentation!");
this.container=document.body;if(a.container){var b=document.getElementById(a.container);b?this.container=b:f("Container is not found. Document body used instead")}this.style.position=a.type&&["fixed","relative","absolute"].includes(a.type)?a.type:this.container!=document.body?"relative":"fixed";this.size=a.size&&["big","medium","small","auto"].includes(a.size)?a.size:"medium";this.animation=!0;this.lastPage=null;void 0===a.border||a.border||(this.style.boxShadow="none");void 0===a.animation||a.animation||
(this.animation=!1,this.style.transition=null);a.position?(a.position.top&&(this.style.top=a.position.top),a.position.bottom&&(this.style.bottom=a.position.bottom),a.position.left&&(this.style.left=a.position.left),a.position.right&&(this.style.right=a.position.right)):["auto","big"].includes(this.size)||this.container!=document.body?(this.style.top="0",this.style.left="0"):(this.style.right="64px",this.style.bottom="0");a.backgroundColor&&(this.style.backgroundColor=a.backgroundColor);for(var d in h[this.size])this.style[d]=
h[this.size][d];this.tray=null;this.trayicon=!0;this.traystyle=JSON.parse(JSON.stringify({backgroundImage:"url(https://webcdn.ringover.com/resources/SDK/icon.svg)",backgroundRepeat:"no-repeat",backgroundSize:"contains",backgroundPosition:"center center",borderRadius:"50%",boxSizing:"border-box",zIndex:"9999",width:"40px",height:"40px",cursor:"pointer",boxShadow:"0px 2px 10px rgba(54, 205, 207, 0.4)",display:"none"}));this.cross=null;void 0===a.trayicon||a.trayicon||(this.trayicon=!1);this.trayicon&&
(a.trayposition?(a.trayposition.top&&(this.traystyle.top=a.trayposition.top),a.trayposition.bottom&&(this.traystyle.bottom=a.trayposition.bottom),a.trayposition.left&&(this.traystyle.left=a.trayposition.left),a.trayposition.right&&(this.traystyle.right=a.trayposition.right)):(this.traystyle.bottom=this.container!=document.body?"-42px":"10px",this.traystyle.right=this.container!=document.body?"-42px":"10px"),this.traystyle.position=this.container!=document.body?"absolute":"fixed",this.tray=u(this.traystyle,
this.id),this.tray.onclick=function(l){return c.show()},this.style.paddingTop="20px","auto"==this.size&&(this.style.height="calc(100% - 20px)"),this.cross=v(this.id),this.cross.onclick=function(l){return c.hide()});a=t(this.style,this.id);this.iframe=a.i;this.iframeContainer=a.d;this.cross&&this.iframeContainer.appendChild(this.cross.parentNode);this.tray&&(this.iframe.dataset.tray=this.tray.id);this.cross&&(this.iframe.dataset.cross=this.cross.id);this.iframe.dataset.animation=this.animation;w(this);
this.iframe.src="https://app.ringover.com"};g.prototype.checkStatus=function(a){a=void 0===a?!1:a;if(this.iframe)switch(this.status){case 1:case 2:return!0;case -1:if(a)return!0;f("Iframe not ready!");break;case 0:f("Iframe not available!");break;default:f()}else f("Iframe not found");return!1};g.prototype.generate=function(){if(this.checkStatus(1)){if(2===this.status)return f("Iframe already present in DOM");this.container.style.position="relative";this.container.appendChild(this.iframeContainer);
this.tray&&this.container.appendChild(this.tray);this.show();this.status=2;return this.iframe}};g.prototype.destroy=function(){this.checkStatus();if(1===this.status)return f("Iframe not found in DOM");this.hide();this.tray&&this.tray.parentNode&&this.tray.parentNode.removeChild(this.tray);this.iframeContainer.parentNode&&this.iframeContainer.parentNode.removeChild(this.iframeContainer);this.status=1;return!0};g.prototype.show=function(){if(this.checkStatus(1))return this.display=m(this.iframeContainer),
this.tray&&(this.tray.style.display="none"),this.isDisplay()};g.prototype.hide=function(){if(this.checkStatus(1)){var a=this.iframeContainer;"false"===a.dataset.animation&&(a.style.display="none");a.style.opacity="0";a.style.maxHeight="0px";this.display=!1;this.tray&&(this.tray.style.display="block");return this.isDisplay()}};g.prototype.toggle=function(a){a=void 0===a?null:a;this.display=null===a?this.display?this.hide():this.show():a?this.show():this.hide();return this.isDisplay()};g.prototype.isDisplay=
function(){return this.display};g.prototype.dial=function(a,c){c=void 0===c?null:c;if(!this.checkStatus())return!1;this.iframe.contentWindow.postMessage({action:"dial",number:a,from_number:c},"https://app.ringover.com");this.display=m(this.iframeContainer);return!0};g.prototype.sendSMS=function(a,c,b){b=void 0===b?null:b;if(!this.checkStatus())return!1;var d=null;c||(d="message");a||(d="to_number");if(d)return console.error("Cannot send a SMS if the "+d+" is not specified"),!1;this.iframe.contentWindow.postMessage({action:"sendSMS",
to_number:a,message:c,from_number:b},"https://app.ringover.com");this.display=m(this.iframeContainer);return!0};g.prototype.openCallLog=function(a){console.log(a);if(!this.checkStatus())return!1;if(!a)return console.error("Cannot open a specific calllog if the call_id is not given")&&!1;console.log("sent event");this.iframe.contentWindow.postMessage({action:"openCallLog",call_id:a},"https://app.ringover.com");this.display=m(this.iframeContainer);return!0};g.prototype.changePage=function(a){if(!this.checkStatus())return!1;
this.iframe.contentWindow.postMessage({action:"changePage",page:a},"https://app.ringover.com");return!0};g.prototype.reload=function(){if(!this.checkStatus())return!1;this.iframe.contentWindow.postMessage({action:"reload"},"https://app.ringover.com");return!0};g.prototype.logout=function(){if(!this.checkStatus())return!1;this.iframe.contentWindow.postMessage({action:"changePage",page:"logout"},"https://app.ringover.com");return!0};g.prototype.getCurrentPage=function(){return this.checkStatus()?this.lastPage:
!1};g.prototype.on=function(a,c){if(!this.checkStatus(1))return!1;k[a]&&k[a].push(c);return!0};g.prototype.off=function(){if(!this.checkStatus(1))return!1;k=q();return!0};return g}();"function"===typeof define&&define.amd?(Object.defineProperty(exports,"__esModule",{value:!0}),define(function(){return e})):"undefined"!==typeof module&&module.exports?module.exports=e:this.RingoverSDK=e})();